### PR TITLE
Add a configurable `frequency` parameter to the geometric model.

### PR DESCRIPTION
**Pull request by etimberg**
If the attribute is unset, default to 60Hz for backwards compatibility.

### CODE REVIEW

**Comment by etimberg** [comment]
@AnjoMan do you know of any IEEE test networks that run at 50Hz? I think that would be a good place to get some data for a test

**Comment by AnjoMan** [comment]
> ## Pull Request Test Coverage Report for [Build 153](https://coveralls.io/builds/24965972)
> 
>     * **2** of **2**   **(100.0%)**  changed or added relevant lines in **1** file are covered.
> 
>     * No unchanged relevant lines lost coverage.
> 
>     * Overall coverage remained the same at **87.5%**
> 
> 
> Totals 	[Coverage Status](https://coveralls.io/builds/24965972)
> Change from base [Build 150](https://coveralls.io/builds/24181911): 	0.0%
> Covered Lines: 	126
> Relevant Lines: 	144
> ##### yellow_heart - [Coveralls](https://coveralls.io)

There is the European LV test network published here: http://sites.ieee.org/pes-testfeeders/resources/

But as far as I can tell there is no geometric data about the line configurations, so we'd have to dig to see if anyone has published those.

**Comment by AnjoMan** [comment]
@etimberg I pushed up a test that I think should pass -- it seems like the off-diagonals of the z_primitive matrix are directly proportional to frequency, so I wrote test checking that. Not sure why, but there is some error in the x term; the r term seems to come out correct.

**Comment by AnjoMan** [comment]
Addresses #26

**Pull request merged**
